image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - install
  - unit-test
  - code-style

Installation:
  stage: install
  tags:
    - rhodan
  script:
    - pip install poetry
    - poetry -V
    - poetry install

Unit tests:
  stage: unit-test
  tags:
    - rhodan
  script:
    - poetry run pytest --cov=py4vasp

Code style:
  stage: code-style
  tags:
    - rhodan
  script:
    - poetry run black --check src
    - poetry run black --check tests

