[tool.poetry]
name = "py4vasp"
version = "0.1.0"
description = ""
authors = ["Martin Schlipf <martin.schlipf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
pytest-cov = "^2.8.1"
[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
