name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry -V
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --cov=py
    - name: Check code style
      run: |
        poetry run black --check src
        poetry run black --check tests
